# Generated by Django 5.0.1 on 2024-05-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_content_post_price_post_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('other', 'Other')], default='Laptop', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='trademark',
            field=models.CharField(choices=[('asus', 'Asus'), ('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('samsung', 'Samsung'), ('apple', 'Apple'), ('other', 'Other')], max_length=20),
        ),
    ]
