# Generated by Django 5.0.1 on 2024-05-14 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_type_post_category_alter_post_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_add', models.PositiveIntegerField(default=0)),
                ('total_delete', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
