# Generated by Django 5.0.1 on 2024-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_actionhistory_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='post_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='post_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='post_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='post_quantity',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='post_trademark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
