# Generated by Django 5.0.1 on 2024-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_actionhistory_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
