# Generated by Django 5.0.1 on 2024-05-16 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 16, 9, 23, 32, 977098, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
