# Generated by Django 5.0.1 on 2024-05-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
