# Generated by Django 5.0.1 on 2024-05-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
