# Generated by Django 5.0.1 on 2024-02-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='body',
        ),
        migrations.AddField(
            model_name='contactform',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
