# Generated by Django 5.0.1 on 2024-03-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_contactform_body_contactform_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactForm',
            new_name='register_models',
        ),
    ]
