# Generated by Django 5.0.1 on 2024-05-26 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_payment_order_remove_shipping_order_and_more'),
        ('product', '0002_actionhistory_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.post'),
            preserve_default=False,
        ),
    ]
