# Generated by Django 5.0.1 on 2024-05-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payments',
        ),
    ]
